version: "3.7"
services:

  mlabs-parking:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    environment: 
      - RAILS_ENV=development
      - NODE_ENV=development
      - TZ=America/Fortaleza
    volumes:
      - ./source/mlabs-parking:/app
    ports:
      - 3000:3000
